server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:gaekdam_project}
    username: ${DB_USERNAME:gaekdam}
    password: ${DB_PASSWORD:gaekdam}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PORT:gaekdam0110}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        # saveAll()을 실제 JDBC batch insert로 묶어주는 옵션
        jdbc:
          batch_size: 500
        # 같은 테이블 insert/update를 묶어 배치 효율 증가
        order_inserts: true
        order_updates: true

        # 더미 생성시 SQL 로그가 (속도 위해 OFF )
        format_sql: false
        show_sql: false

        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: never


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.gaekdam.gaekdambe.**


jwt:
  secret: ${JWT_SECRET:og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30t}
  access-expiration: 900000      # 15?
  #  access-expiration: 10000      # 10초
  refresh-expiration: 259200000   # 3일

crypto:
  hmac:
    pepper-b64: ${CRYPTO_HMAC_PEPPER_B64:og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30=}
  local-kek:
    key-b64: ${CRYPTO_LOCAL_KEK_B64:P32UXwOxycfN2L772hcLLC+jPcaaOzAzWiL2jdjPm+o=}

logging:
  level:
    org.apache.coyote.http11: DEBUG
    org.apache.tomcat.util.http.parser: DEBUG
    org.apache.tomcat.util.net: INFO