name: gaekdam-be CI (Testcontainers)

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - run: ./gradlew test --no-daemon

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test

    env:
      JWT_SECRET_B64: og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30=
      CRYPTO_HMAC_PEPPER_B64: og9OBhk6xH4Quwa+mWk37sISpvQ2C0ONg5l6jJRCf30=
      CRYPTO_LOCAL_KEK_B64: P32UXwOxycfN2L772hcLLC+jPcaaOzAzWiL2jdjPm+o=

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle


      - run: |
          ./gradlew integrationTest --no-daemon \
            -DJWT_SECRET_B64=${JWT_SECRET_B64} \
            -DCRYPTO_HMAC_PEPPER_B64=${CRYPTO_HMAC_PEPPER_B64} \
            -DCRYPTO_LOCAL_KEK_B64=${CRYPTO_LOCAL_KEK_B64} \
            -Dspring.data.redis.host=localhost \
            -Dspring.data.redis.port=6379 \
            -Dmanagement.health.redis.enabled=false
